stages:
  - test

coverage:
  stage: test
  variables:
    ABI_CSV: "contract-abi/build/reports/jacoco/test/jacocoTestReport.csv"
    MIRROR_CSV: "mirror/build/reports/jacoco/test/jacocoTestReport.csv"
  script:
    - ls -allh
    - ./gradlew check
    - cat "$ABI_CSV" "$MIRROR_CSV" | awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }'
  coverage: '/^([0-9]{1,3}\.*[0-9]*).% covered/'
  artifacts:
    paths:
      - contract-abi/build/jacocoHtml
      - contract-abi/build/reports
      - mirror/build/jacocoHtml
      - mirror/build/reports
    when: on_success
    expire_in: 1 day
