stages:
  - test

coverage:
  stage: test
  variables:
    COVERAGE_CSV: "build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.csv"
  script:
    - ls -allh
    - ./gradlew check
    - cat "$COVERAGE_CSV" | awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }'
  coverage: '/^([0-9]{1,3}\.*[0-9]*).% covered/'
  artifacts:
    paths:
      - build/reports
    when: on_success
    expire_in: 1 day
