// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/contract/proposal_contract.proto

package org.tron.sunio.tronsdk.protos.contract;

public final class ProposalContract {
  private ProposalContract() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProposalApproveContractOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ProposalApproveContract)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes owner_address = 1;</code>
     * @return The ownerAddress.
     */
    com.google.protobuf.ByteString getOwnerAddress();

    /**
     * <code>int64 proposal_id = 2;</code>
     * @return The proposalId.
     */
    long getProposalId();

    /**
     * <pre>
     * add or remove approval
     * </pre>
     *
     * <code>bool is_add_approval = 3;</code>
     * @return The isAddApproval.
     */
    boolean getIsAddApproval();
  }
  /**
   * Protobuf type {@code protocol.ProposalApproveContract}
   */
  public static final class ProposalApproveContract extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.ProposalApproveContract)
      ProposalApproveContractOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProposalApproveContract.newBuilder() to construct.
    private ProposalApproveContract(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProposalApproveContract() {
      ownerAddress_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProposalApproveContract();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProposalApproveContract(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              ownerAddress_ = input.readBytes();
              break;
            }
            case 16: {

              proposalId_ = input.readInt64();
              break;
            }
            case 24: {

              isAddApproval_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalApproveContract_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalApproveContract_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract.class, org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract.Builder.class);
    }

    public static final int OWNER_ADDRESS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString ownerAddress_;
    /**
     * <code>bytes owner_address = 1;</code>
     * @return The ownerAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOwnerAddress() {
      return ownerAddress_;
    }

    public static final int PROPOSAL_ID_FIELD_NUMBER = 2;
    private long proposalId_;
    /**
     * <code>int64 proposal_id = 2;</code>
     * @return The proposalId.
     */
    @java.lang.Override
    public long getProposalId() {
      return proposalId_;
    }

    public static final int IS_ADD_APPROVAL_FIELD_NUMBER = 3;
    private boolean isAddApproval_;
    /**
     * <pre>
     * add or remove approval
     * </pre>
     *
     * <code>bool is_add_approval = 3;</code>
     * @return The isAddApproval.
     */
    @java.lang.Override
    public boolean getIsAddApproval() {
      return isAddApproval_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!ownerAddress_.isEmpty()) {
        output.writeBytes(1, ownerAddress_);
      }
      if (proposalId_ != 0L) {
        output.writeInt64(2, proposalId_);
      }
      if (isAddApproval_ != false) {
        output.writeBool(3, isAddApproval_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!ownerAddress_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, ownerAddress_);
      }
      if (proposalId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, proposalId_);
      }
      if (isAddApproval_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isAddApproval_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract)) {
        return super.equals(obj);
      }
      org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract other = (org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract) obj;

      if (!getOwnerAddress()
          .equals(other.getOwnerAddress())) return false;
      if (getProposalId()
          != other.getProposalId()) return false;
      if (getIsAddApproval()
          != other.getIsAddApproval()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OWNER_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getOwnerAddress().hashCode();
      hash = (37 * hash) + PROPOSAL_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProposalId());
      hash = (37 * hash) + IS_ADD_APPROVAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsAddApproval());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ProposalApproveContract}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ProposalApproveContract)
        org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContractOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalApproveContract_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalApproveContract_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract.class, org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract.Builder.class);
      }

      // Construct using org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ownerAddress_ = com.google.protobuf.ByteString.EMPTY;

        proposalId_ = 0L;

        isAddApproval_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalApproveContract_descriptor;
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract getDefaultInstanceForType() {
        return org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract.getDefaultInstance();
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract build() {
        org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract buildPartial() {
        org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract result = new org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract(this);
        result.ownerAddress_ = ownerAddress_;
        result.proposalId_ = proposalId_;
        result.isAddApproval_ = isAddApproval_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract) {
          return mergeFrom((org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract other) {
        if (other == org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract.getDefaultInstance()) return this;
        if (other.getOwnerAddress() != com.google.protobuf.ByteString.EMPTY) {
          setOwnerAddress(other.getOwnerAddress());
        }
        if (other.getProposalId() != 0L) {
          setProposalId(other.getProposalId());
        }
        if (other.getIsAddApproval() != false) {
          setIsAddApproval(other.getIsAddApproval());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString ownerAddress_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes owner_address = 1;</code>
       * @return The ownerAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getOwnerAddress() {
        return ownerAddress_;
      }
      /**
       * <code>bytes owner_address = 1;</code>
       * @param value The ownerAddress to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ownerAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes owner_address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerAddress() {
        
        ownerAddress_ = getDefaultInstance().getOwnerAddress();
        onChanged();
        return this;
      }

      private long proposalId_ ;
      /**
       * <code>int64 proposal_id = 2;</code>
       * @return The proposalId.
       */
      @java.lang.Override
      public long getProposalId() {
        return proposalId_;
      }
      /**
       * <code>int64 proposal_id = 2;</code>
       * @param value The proposalId to set.
       * @return This builder for chaining.
       */
      public Builder setProposalId(long value) {
        
        proposalId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 proposal_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProposalId() {
        
        proposalId_ = 0L;
        onChanged();
        return this;
      }

      private boolean isAddApproval_ ;
      /**
       * <pre>
       * add or remove approval
       * </pre>
       *
       * <code>bool is_add_approval = 3;</code>
       * @return The isAddApproval.
       */
      @java.lang.Override
      public boolean getIsAddApproval() {
        return isAddApproval_;
      }
      /**
       * <pre>
       * add or remove approval
       * </pre>
       *
       * <code>bool is_add_approval = 3;</code>
       * @param value The isAddApproval to set.
       * @return This builder for chaining.
       */
      public Builder setIsAddApproval(boolean value) {
        
        isAddApproval_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * add or remove approval
       * </pre>
       *
       * <code>bool is_add_approval = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsAddApproval() {
        
        isAddApproval_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.ProposalApproveContract)
    }

    // @@protoc_insertion_point(class_scope:protocol.ProposalApproveContract)
    private static final org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract();
    }

    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProposalApproveContract>
        PARSER = new com.google.protobuf.AbstractParser<ProposalApproveContract>() {
      @java.lang.Override
      public ProposalApproveContract parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProposalApproveContract(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProposalApproveContract> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProposalApproveContract> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalApproveContract getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProposalCreateContractOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ProposalCreateContract)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes owner_address = 1;</code>
     * @return The ownerAddress.
     */
    com.google.protobuf.ByteString getOwnerAddress();

    /**
     * <code>map&lt;int64, int64&gt; parameters = 2;</code>
     */
    int getParametersCount();
    /**
     * <code>map&lt;int64, int64&gt; parameters = 2;</code>
     */
    boolean containsParameters(
        long key);
    /**
     * Use {@link #getParametersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Long, java.lang.Long>
    getParameters();
    /**
     * <code>map&lt;int64, int64&gt; parameters = 2;</code>
     */
    java.util.Map<java.lang.Long, java.lang.Long>
    getParametersMap();
    /**
     * <code>map&lt;int64, int64&gt; parameters = 2;</code>
     */

    long getParametersOrDefault(
        long key,
        long defaultValue);
    /**
     * <code>map&lt;int64, int64&gt; parameters = 2;</code>
     */

    long getParametersOrThrow(
        long key);
  }
  /**
   * Protobuf type {@code protocol.ProposalCreateContract}
   */
  public static final class ProposalCreateContract extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.ProposalCreateContract)
      ProposalCreateContractOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProposalCreateContract.newBuilder() to construct.
    private ProposalCreateContract(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProposalCreateContract() {
      ownerAddress_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProposalCreateContract();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProposalCreateContract(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              ownerAddress_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                parameters_ = com.google.protobuf.MapField.newMapField(
                    ParametersDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Long, java.lang.Long>
              parameters__ = input.readMessage(
                  ParametersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              parameters_.getMutableMap().put(
                  parameters__.getKey(), parameters__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalCreateContract_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetParameters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalCreateContract_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract.class, org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract.Builder.class);
    }

    public static final int OWNER_ADDRESS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString ownerAddress_;
    /**
     * <code>bytes owner_address = 1;</code>
     * @return The ownerAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOwnerAddress() {
      return ownerAddress_;
    }

    public static final int PARAMETERS_FIELD_NUMBER = 2;
    private static final class ParametersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Long, java.lang.Long> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Long, java.lang.Long>newDefaultInstance(
                  org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalCreateContract_ParametersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L,
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L);
    }
    private com.google.protobuf.MapField<
        java.lang.Long, java.lang.Long> parameters_;
    private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
    internalGetParameters() {
      if (parameters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParametersDefaultEntryHolder.defaultEntry);
      }
      return parameters_;
    }

    public int getParametersCount() {
      return internalGetParameters().getMap().size();
    }
    /**
     * <code>map&lt;int64, int64&gt; parameters = 2;</code>
     */

    @java.lang.Override
    public boolean containsParameters(
        long key) {
      
      return internalGetParameters().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParametersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Long> getParameters() {
      return getParametersMap();
    }
    /**
     * <code>map&lt;int64, int64&gt; parameters = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Long, java.lang.Long> getParametersMap() {
      return internalGetParameters().getMap();
    }
    /**
     * <code>map&lt;int64, int64&gt; parameters = 2;</code>
     */
    @java.lang.Override

    public long getParametersOrDefault(
        long key,
        long defaultValue) {
      
      java.util.Map<java.lang.Long, java.lang.Long> map =
          internalGetParameters().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, int64&gt; parameters = 2;</code>
     */
    @java.lang.Override

    public long getParametersOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, java.lang.Long> map =
          internalGetParameters().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!ownerAddress_.isEmpty()) {
        output.writeBytes(1, ownerAddress_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeLongMapTo(
          output,
          internalGetParameters(),
          ParametersDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!ownerAddress_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, ownerAddress_);
      }
      for (java.util.Map.Entry<java.lang.Long, java.lang.Long> entry
           : internalGetParameters().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Long, java.lang.Long>
        parameters__ = ParametersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, parameters__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract)) {
        return super.equals(obj);
      }
      org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract other = (org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract) obj;

      if (!getOwnerAddress()
          .equals(other.getOwnerAddress())) return false;
      if (!internalGetParameters().equals(
          other.internalGetParameters())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OWNER_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getOwnerAddress().hashCode();
      if (!internalGetParameters().getMap().isEmpty()) {
        hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetParameters().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ProposalCreateContract}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ProposalCreateContract)
        org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContractOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalCreateContract_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetParameters();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableParameters();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalCreateContract_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract.class, org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract.Builder.class);
      }

      // Construct using org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ownerAddress_ = com.google.protobuf.ByteString.EMPTY;

        internalGetMutableParameters().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalCreateContract_descriptor;
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract getDefaultInstanceForType() {
        return org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract.getDefaultInstance();
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract build() {
        org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract buildPartial() {
        org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract result = new org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract(this);
        int from_bitField0_ = bitField0_;
        result.ownerAddress_ = ownerAddress_;
        result.parameters_ = internalGetParameters();
        result.parameters_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract) {
          return mergeFrom((org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract other) {
        if (other == org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract.getDefaultInstance()) return this;
        if (other.getOwnerAddress() != com.google.protobuf.ByteString.EMPTY) {
          setOwnerAddress(other.getOwnerAddress());
        }
        internalGetMutableParameters().mergeFrom(
            other.internalGetParameters());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString ownerAddress_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes owner_address = 1;</code>
       * @return The ownerAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getOwnerAddress() {
        return ownerAddress_;
      }
      /**
       * <code>bytes owner_address = 1;</code>
       * @param value The ownerAddress to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ownerAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes owner_address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerAddress() {
        
        ownerAddress_ = getDefaultInstance().getOwnerAddress();
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Long, java.lang.Long> parameters_;
      private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
      internalGetParameters() {
        if (parameters_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ParametersDefaultEntryHolder.defaultEntry);
        }
        return parameters_;
      }
      private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
      internalGetMutableParameters() {
        onChanged();;
        if (parameters_ == null) {
          parameters_ = com.google.protobuf.MapField.newMapField(
              ParametersDefaultEntryHolder.defaultEntry);
        }
        if (!parameters_.isMutable()) {
          parameters_ = parameters_.copy();
        }
        return parameters_;
      }

      public int getParametersCount() {
        return internalGetParameters().getMap().size();
      }
      /**
       * <code>map&lt;int64, int64&gt; parameters = 2;</code>
       */

      @java.lang.Override
      public boolean containsParameters(
          long key) {
        
        return internalGetParameters().getMap().containsKey(key);
      }
      /**
       * Use {@link #getParametersMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, java.lang.Long> getParameters() {
        return getParametersMap();
      }
      /**
       * <code>map&lt;int64, int64&gt; parameters = 2;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Long, java.lang.Long> getParametersMap() {
        return internalGetParameters().getMap();
      }
      /**
       * <code>map&lt;int64, int64&gt; parameters = 2;</code>
       */
      @java.lang.Override

      public long getParametersOrDefault(
          long key,
          long defaultValue) {
        
        java.util.Map<java.lang.Long, java.lang.Long> map =
            internalGetParameters().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int64, int64&gt; parameters = 2;</code>
       */
      @java.lang.Override

      public long getParametersOrThrow(
          long key) {
        
        java.util.Map<java.lang.Long, java.lang.Long> map =
            internalGetParameters().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearParameters() {
        internalGetMutableParameters().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int64, int64&gt; parameters = 2;</code>
       */

      public Builder removeParameters(
          long key) {
        
        internalGetMutableParameters().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, java.lang.Long>
      getMutableParameters() {
        return internalGetMutableParameters().getMutableMap();
      }
      /**
       * <code>map&lt;int64, int64&gt; parameters = 2;</code>
       */
      public Builder putParameters(
          long key,
          long value) {
        
        
        internalGetMutableParameters().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int64, int64&gt; parameters = 2;</code>
       */

      public Builder putAllParameters(
          java.util.Map<java.lang.Long, java.lang.Long> values) {
        internalGetMutableParameters().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.ProposalCreateContract)
    }

    // @@protoc_insertion_point(class_scope:protocol.ProposalCreateContract)
    private static final org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract();
    }

    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProposalCreateContract>
        PARSER = new com.google.protobuf.AbstractParser<ProposalCreateContract>() {
      @java.lang.Override
      public ProposalCreateContract parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProposalCreateContract(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProposalCreateContract> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProposalCreateContract> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalCreateContract getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProposalDeleteContractOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ProposalDeleteContract)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes owner_address = 1;</code>
     * @return The ownerAddress.
     */
    com.google.protobuf.ByteString getOwnerAddress();

    /**
     * <code>int64 proposal_id = 2;</code>
     * @return The proposalId.
     */
    long getProposalId();
  }
  /**
   * Protobuf type {@code protocol.ProposalDeleteContract}
   */
  public static final class ProposalDeleteContract extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.ProposalDeleteContract)
      ProposalDeleteContractOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProposalDeleteContract.newBuilder() to construct.
    private ProposalDeleteContract(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProposalDeleteContract() {
      ownerAddress_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProposalDeleteContract();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProposalDeleteContract(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              ownerAddress_ = input.readBytes();
              break;
            }
            case 16: {

              proposalId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalDeleteContract_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalDeleteContract_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract.class, org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract.Builder.class);
    }

    public static final int OWNER_ADDRESS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString ownerAddress_;
    /**
     * <code>bytes owner_address = 1;</code>
     * @return The ownerAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOwnerAddress() {
      return ownerAddress_;
    }

    public static final int PROPOSAL_ID_FIELD_NUMBER = 2;
    private long proposalId_;
    /**
     * <code>int64 proposal_id = 2;</code>
     * @return The proposalId.
     */
    @java.lang.Override
    public long getProposalId() {
      return proposalId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!ownerAddress_.isEmpty()) {
        output.writeBytes(1, ownerAddress_);
      }
      if (proposalId_ != 0L) {
        output.writeInt64(2, proposalId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!ownerAddress_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, ownerAddress_);
      }
      if (proposalId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, proposalId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract)) {
        return super.equals(obj);
      }
      org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract other = (org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract) obj;

      if (!getOwnerAddress()
          .equals(other.getOwnerAddress())) return false;
      if (getProposalId()
          != other.getProposalId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OWNER_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getOwnerAddress().hashCode();
      hash = (37 * hash) + PROPOSAL_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProposalId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ProposalDeleteContract}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ProposalDeleteContract)
        org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContractOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalDeleteContract_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalDeleteContract_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract.class, org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract.Builder.class);
      }

      // Construct using org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ownerAddress_ = com.google.protobuf.ByteString.EMPTY;

        proposalId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tron.sunio.tronsdk.protos.contract.ProposalContract.internal_static_protocol_ProposalDeleteContract_descriptor;
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract getDefaultInstanceForType() {
        return org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract.getDefaultInstance();
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract build() {
        org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract buildPartial() {
        org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract result = new org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract(this);
        result.ownerAddress_ = ownerAddress_;
        result.proposalId_ = proposalId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract) {
          return mergeFrom((org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract other) {
        if (other == org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract.getDefaultInstance()) return this;
        if (other.getOwnerAddress() != com.google.protobuf.ByteString.EMPTY) {
          setOwnerAddress(other.getOwnerAddress());
        }
        if (other.getProposalId() != 0L) {
          setProposalId(other.getProposalId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString ownerAddress_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes owner_address = 1;</code>
       * @return The ownerAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getOwnerAddress() {
        return ownerAddress_;
      }
      /**
       * <code>bytes owner_address = 1;</code>
       * @param value The ownerAddress to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ownerAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes owner_address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerAddress() {
        
        ownerAddress_ = getDefaultInstance().getOwnerAddress();
        onChanged();
        return this;
      }

      private long proposalId_ ;
      /**
       * <code>int64 proposal_id = 2;</code>
       * @return The proposalId.
       */
      @java.lang.Override
      public long getProposalId() {
        return proposalId_;
      }
      /**
       * <code>int64 proposal_id = 2;</code>
       * @param value The proposalId to set.
       * @return This builder for chaining.
       */
      public Builder setProposalId(long value) {
        
        proposalId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 proposal_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProposalId() {
        
        proposalId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.ProposalDeleteContract)
    }

    // @@protoc_insertion_point(class_scope:protocol.ProposalDeleteContract)
    private static final org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract();
    }

    public static org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProposalDeleteContract>
        PARSER = new com.google.protobuf.AbstractParser<ProposalDeleteContract>() {
      @java.lang.Override
      public ProposalDeleteContract parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProposalDeleteContract(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProposalDeleteContract> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProposalDeleteContract> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tron.sunio.tronsdk.protos.contract.ProposalContract.ProposalDeleteContract getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ProposalApproveContract_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ProposalApproveContract_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ProposalCreateContract_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ProposalCreateContract_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ProposalCreateContract_ParametersEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ProposalCreateContract_ParametersEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ProposalDeleteContract_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ProposalDeleteContract_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%core/contract/proposal_contract.proto\022" +
      "\010protocol\"^\n\027ProposalApproveContract\022\025\n\r" +
      "owner_address\030\001 \001(\014\022\023\n\013proposal_id\030\002 \001(\003" +
      "\022\027\n\017is_add_approval\030\003 \001(\010\"\250\001\n\026ProposalCr" +
      "eateContract\022\025\n\rowner_address\030\001 \001(\014\022D\n\np" +
      "arameters\030\002 \003(\01320.protocol.ProposalCreat" +
      "eContract.ParametersEntry\0321\n\017ParametersE" +
      "ntry\022\013\n\003key\030\001 \001(\003\022\r\n\005value\030\002 \001(\003:\0028\001\"D\n\026" +
      "ProposalDeleteContract\022\025\n\rowner_address\030" +
      "\001 \001(\014\022\023\n\013proposal_id\030\002 \001(\003BS\n&org.tron.s" +
      "unio.tronsdk.protos.contractZ)github.com" +
      "/tronprotocol/grpc-gateway/coreb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_ProposalApproveContract_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_ProposalApproveContract_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ProposalApproveContract_descriptor,
        new java.lang.String[] { "OwnerAddress", "ProposalId", "IsAddApproval", });
    internal_static_protocol_ProposalCreateContract_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_ProposalCreateContract_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ProposalCreateContract_descriptor,
        new java.lang.String[] { "OwnerAddress", "Parameters", });
    internal_static_protocol_ProposalCreateContract_ParametersEntry_descriptor =
      internal_static_protocol_ProposalCreateContract_descriptor.getNestedTypes().get(0);
    internal_static_protocol_ProposalCreateContract_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ProposalCreateContract_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_protocol_ProposalDeleteContract_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_ProposalDeleteContract_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ProposalDeleteContract_descriptor,
        new java.lang.String[] { "OwnerAddress", "ProposalId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
