// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/contract/vote_asset_contract.proto

package org.tron.sunio.tronsdk.protos.contract;

public final class VoteAssetContractOuterClass {
  private VoteAssetContractOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VoteAssetContractOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.VoteAssetContract)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes owner_address = 1;</code>
     * @return The ownerAddress.
     */
    com.google.protobuf.ByteString getOwnerAddress();

    /**
     * <code>repeated bytes vote_address = 2;</code>
     * @return A list containing the voteAddress.
     */
    java.util.List<com.google.protobuf.ByteString> getVoteAddressList();
    /**
     * <code>repeated bytes vote_address = 2;</code>
     * @return The count of voteAddress.
     */
    int getVoteAddressCount();
    /**
     * <code>repeated bytes vote_address = 2;</code>
     * @param index The index of the element to return.
     * @return The voteAddress at the given index.
     */
    com.google.protobuf.ByteString getVoteAddress(int index);

    /**
     * <code>bool support = 3;</code>
     * @return The support.
     */
    boolean getSupport();

    /**
     * <code>int32 count = 5;</code>
     * @return The count.
     */
    int getCount();
  }
  /**
   * Protobuf type {@code protocol.VoteAssetContract}
   */
  public static final class VoteAssetContract extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.VoteAssetContract)
      VoteAssetContractOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VoteAssetContract.newBuilder() to construct.
    private VoteAssetContract(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoteAssetContract() {
      ownerAddress_ = com.google.protobuf.ByteString.EMPTY;
      voteAddress_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VoteAssetContract();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VoteAssetContract(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              ownerAddress_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                voteAddress_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              voteAddress_.add(input.readBytes());
              break;
            }
            case 24: {

              support_ = input.readBool();
              break;
            }
            case 40: {

              count_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          voteAddress_ = java.util.Collections.unmodifiableList(voteAddress_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.internal_static_protocol_VoteAssetContract_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.internal_static_protocol_VoteAssetContract_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract.class, org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract.Builder.class);
    }

    public static final int OWNER_ADDRESS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString ownerAddress_;
    /**
     * <code>bytes owner_address = 1;</code>
     * @return The ownerAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOwnerAddress() {
      return ownerAddress_;
    }

    public static final int VOTE_ADDRESS_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> voteAddress_;
    /**
     * <code>repeated bytes vote_address = 2;</code>
     * @return A list containing the voteAddress.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getVoteAddressList() {
      return voteAddress_;
    }
    /**
     * <code>repeated bytes vote_address = 2;</code>
     * @return The count of voteAddress.
     */
    public int getVoteAddressCount() {
      return voteAddress_.size();
    }
    /**
     * <code>repeated bytes vote_address = 2;</code>
     * @param index The index of the element to return.
     * @return The voteAddress at the given index.
     */
    public com.google.protobuf.ByteString getVoteAddress(int index) {
      return voteAddress_.get(index);
    }

    public static final int SUPPORT_FIELD_NUMBER = 3;
    private boolean support_;
    /**
     * <code>bool support = 3;</code>
     * @return The support.
     */
    @java.lang.Override
    public boolean getSupport() {
      return support_;
    }

    public static final int COUNT_FIELD_NUMBER = 5;
    private int count_;
    /**
     * <code>int32 count = 5;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!ownerAddress_.isEmpty()) {
        output.writeBytes(1, ownerAddress_);
      }
      for (int i = 0; i < voteAddress_.size(); i++) {
        output.writeBytes(2, voteAddress_.get(i));
      }
      if (support_ != false) {
        output.writeBool(3, support_);
      }
      if (count_ != 0) {
        output.writeInt32(5, count_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!ownerAddress_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, ownerAddress_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < voteAddress_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(voteAddress_.get(i));
        }
        size += dataSize;
        size += 1 * getVoteAddressList().size();
      }
      if (support_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, support_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, count_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract)) {
        return super.equals(obj);
      }
      org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract other = (org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract) obj;

      if (!getOwnerAddress()
          .equals(other.getOwnerAddress())) return false;
      if (!getVoteAddressList()
          .equals(other.getVoteAddressList())) return false;
      if (getSupport()
          != other.getSupport()) return false;
      if (getCount()
          != other.getCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OWNER_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getOwnerAddress().hashCode();
      if (getVoteAddressCount() > 0) {
        hash = (37 * hash) + VOTE_ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getVoteAddressList().hashCode();
      }
      hash = (37 * hash) + SUPPORT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSupport());
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.VoteAssetContract}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.VoteAssetContract)
        org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContractOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.internal_static_protocol_VoteAssetContract_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.internal_static_protocol_VoteAssetContract_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract.class, org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract.Builder.class);
      }

      // Construct using org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ownerAddress_ = com.google.protobuf.ByteString.EMPTY;

        voteAddress_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        support_ = false;

        count_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.internal_static_protocol_VoteAssetContract_descriptor;
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract getDefaultInstanceForType() {
        return org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract.getDefaultInstance();
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract build() {
        org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract buildPartial() {
        org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract result = new org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract(this);
        int from_bitField0_ = bitField0_;
        result.ownerAddress_ = ownerAddress_;
        if (((bitField0_ & 0x00000001) != 0)) {
          voteAddress_ = java.util.Collections.unmodifiableList(voteAddress_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.voteAddress_ = voteAddress_;
        result.support_ = support_;
        result.count_ = count_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract) {
          return mergeFrom((org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract other) {
        if (other == org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract.getDefaultInstance()) return this;
        if (other.getOwnerAddress() != com.google.protobuf.ByteString.EMPTY) {
          setOwnerAddress(other.getOwnerAddress());
        }
        if (!other.voteAddress_.isEmpty()) {
          if (voteAddress_.isEmpty()) {
            voteAddress_ = other.voteAddress_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVoteAddressIsMutable();
            voteAddress_.addAll(other.voteAddress_);
          }
          onChanged();
        }
        if (other.getSupport() != false) {
          setSupport(other.getSupport());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString ownerAddress_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes owner_address = 1;</code>
       * @return The ownerAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getOwnerAddress() {
        return ownerAddress_;
      }
      /**
       * <code>bytes owner_address = 1;</code>
       * @param value The ownerAddress to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ownerAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes owner_address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerAddress() {
        
        ownerAddress_ = getDefaultInstance().getOwnerAddress();
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> voteAddress_ = java.util.Collections.emptyList();
      private void ensureVoteAddressIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          voteAddress_ = new java.util.ArrayList<com.google.protobuf.ByteString>(voteAddress_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes vote_address = 2;</code>
       * @return A list containing the voteAddress.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getVoteAddressList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(voteAddress_) : voteAddress_;
      }
      /**
       * <code>repeated bytes vote_address = 2;</code>
       * @return The count of voteAddress.
       */
      public int getVoteAddressCount() {
        return voteAddress_.size();
      }
      /**
       * <code>repeated bytes vote_address = 2;</code>
       * @param index The index of the element to return.
       * @return The voteAddress at the given index.
       */
      public com.google.protobuf.ByteString getVoteAddress(int index) {
        return voteAddress_.get(index);
      }
      /**
       * <code>repeated bytes vote_address = 2;</code>
       * @param index The index to set the value at.
       * @param value The voteAddress to set.
       * @return This builder for chaining.
       */
      public Builder setVoteAddress(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVoteAddressIsMutable();
        voteAddress_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes vote_address = 2;</code>
       * @param value The voteAddress to add.
       * @return This builder for chaining.
       */
      public Builder addVoteAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVoteAddressIsMutable();
        voteAddress_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes vote_address = 2;</code>
       * @param values The voteAddress to add.
       * @return This builder for chaining.
       */
      public Builder addAllVoteAddress(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureVoteAddressIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, voteAddress_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes vote_address = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteAddress() {
        voteAddress_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private boolean support_ ;
      /**
       * <code>bool support = 3;</code>
       * @return The support.
       */
      @java.lang.Override
      public boolean getSupport() {
        return support_;
      }
      /**
       * <code>bool support = 3;</code>
       * @param value The support to set.
       * @return This builder for chaining.
       */
      public Builder setSupport(boolean value) {
        
        support_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool support = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSupport() {
        
        support_ = false;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>int32 count = 5;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 5;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.VoteAssetContract)
    }

    // @@protoc_insertion_point(class_scope:protocol.VoteAssetContract)
    private static final org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract();
    }

    public static org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VoteAssetContract>
        PARSER = new com.google.protobuf.AbstractParser<VoteAssetContract>() {
      @java.lang.Override
      public VoteAssetContract parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoteAssetContract(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VoteAssetContract> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VoteAssetContract> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tron.sunio.tronsdk.protos.contract.VoteAssetContractOuterClass.VoteAssetContract getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_VoteAssetContract_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_VoteAssetContract_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'core/contract/vote_asset_contract.prot" +
      "o\022\010protocol\"`\n\021VoteAssetContract\022\025\n\rowne" +
      "r_address\030\001 \001(\014\022\024\n\014vote_address\030\002 \003(\014\022\017\n" +
      "\007support\030\003 \001(\010\022\r\n\005count\030\005 \001(\005BS\n&org.tro" +
      "n.sunio.tronsdk.protos.contractZ)github." +
      "com/tronprotocol/grpc-gateway/coreb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_VoteAssetContract_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_VoteAssetContract_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_VoteAssetContract_descriptor,
        new java.lang.String[] { "OwnerAddress", "VoteAddress", "Support", "Count", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
