// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/zksnark.proto

package org.tron.sunio.tronsdk.api;

public final class ZksnarkGrpcAPI {
  private ZksnarkGrpcAPI() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ZksnarkRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ZksnarkRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.protocol.Transaction transaction = 1;</code>
     * @return Whether the transaction field is set.
     */
    boolean hasTransaction();
    /**
     * <code>.protocol.Transaction transaction = 1;</code>
     * @return The transaction.
     */
    org.tron.sunio.tronsdk.protos.Protocol.Transaction getTransaction();
    /**
     * <code>.protocol.Transaction transaction = 1;</code>
     */
    org.tron.sunio.tronsdk.protos.Protocol.TransactionOrBuilder getTransactionOrBuilder();

    /**
     * <code>bytes sighash = 2;</code>
     * @return The sighash.
     */
    com.google.protobuf.ByteString getSighash();

    /**
     * <code>int64 valueBalance = 3;</code>
     * @return The valueBalance.
     */
    long getValueBalance();

    /**
     * <code>string txId = 4;</code>
     * @return The txId.
     */
    java.lang.String getTxId();
    /**
     * <code>string txId = 4;</code>
     * @return The bytes for txId.
     */
    com.google.protobuf.ByteString
        getTxIdBytes();
  }
  /**
   * Protobuf type {@code protocol.ZksnarkRequest}
   */
  public static final class ZksnarkRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.ZksnarkRequest)
      ZksnarkRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ZksnarkRequest.newBuilder() to construct.
    private ZksnarkRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ZksnarkRequest() {
      sighash_ = com.google.protobuf.ByteString.EMPTY;
      txId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ZksnarkRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ZksnarkRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.tron.sunio.tronsdk.protos.Protocol.Transaction.Builder subBuilder = null;
              if (transaction_ != null) {
                subBuilder = transaction_.toBuilder();
              }
              transaction_ = input.readMessage(org.tron.sunio.tronsdk.protos.Protocol.Transaction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(transaction_);
                transaction_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              sighash_ = input.readBytes();
              break;
            }
            case 24: {

              valueBalance_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              txId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.internal_static_protocol_ZksnarkRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.internal_static_protocol_ZksnarkRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest.class, org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest.Builder.class);
    }

    public static final int TRANSACTION_FIELD_NUMBER = 1;
    private org.tron.sunio.tronsdk.protos.Protocol.Transaction transaction_;
    /**
     * <code>.protocol.Transaction transaction = 1;</code>
     * @return Whether the transaction field is set.
     */
    @java.lang.Override
    public boolean hasTransaction() {
      return transaction_ != null;
    }
    /**
     * <code>.protocol.Transaction transaction = 1;</code>
     * @return The transaction.
     */
    @java.lang.Override
    public org.tron.sunio.tronsdk.protos.Protocol.Transaction getTransaction() {
      return transaction_ == null ? org.tron.sunio.tronsdk.protos.Protocol.Transaction.getDefaultInstance() : transaction_;
    }
    /**
     * <code>.protocol.Transaction transaction = 1;</code>
     */
    @java.lang.Override
    public org.tron.sunio.tronsdk.protos.Protocol.TransactionOrBuilder getTransactionOrBuilder() {
      return getTransaction();
    }

    public static final int SIGHASH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString sighash_;
    /**
     * <code>bytes sighash = 2;</code>
     * @return The sighash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSighash() {
      return sighash_;
    }

    public static final int VALUEBALANCE_FIELD_NUMBER = 3;
    private long valueBalance_;
    /**
     * <code>int64 valueBalance = 3;</code>
     * @return The valueBalance.
     */
    @java.lang.Override
    public long getValueBalance() {
      return valueBalance_;
    }

    public static final int TXID_FIELD_NUMBER = 4;
    private volatile java.lang.Object txId_;
    /**
     * <code>string txId = 4;</code>
     * @return The txId.
     */
    @java.lang.Override
    public java.lang.String getTxId() {
      java.lang.Object ref = txId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txId_ = s;
        return s;
      }
    }
    /**
     * <code>string txId = 4;</code>
     * @return The bytes for txId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTxIdBytes() {
      java.lang.Object ref = txId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (transaction_ != null) {
        output.writeMessage(1, getTransaction());
      }
      if (!sighash_.isEmpty()) {
        output.writeBytes(2, sighash_);
      }
      if (valueBalance_ != 0L) {
        output.writeInt64(3, valueBalance_);
      }
      if (!getTxIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, txId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (transaction_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTransaction());
      }
      if (!sighash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, sighash_);
      }
      if (valueBalance_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, valueBalance_);
      }
      if (!getTxIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, txId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest)) {
        return super.equals(obj);
      }
      org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest other = (org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest) obj;

      if (hasTransaction() != other.hasTransaction()) return false;
      if (hasTransaction()) {
        if (!getTransaction()
            .equals(other.getTransaction())) return false;
      }
      if (!getSighash()
          .equals(other.getSighash())) return false;
      if (getValueBalance()
          != other.getValueBalance()) return false;
      if (!getTxId()
          .equals(other.getTxId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTransaction()) {
        hash = (37 * hash) + TRANSACTION_FIELD_NUMBER;
        hash = (53 * hash) + getTransaction().hashCode();
      }
      hash = (37 * hash) + SIGHASH_FIELD_NUMBER;
      hash = (53 * hash) + getSighash().hashCode();
      hash = (37 * hash) + VALUEBALANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValueBalance());
      hash = (37 * hash) + TXID_FIELD_NUMBER;
      hash = (53 * hash) + getTxId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ZksnarkRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ZksnarkRequest)
        org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.internal_static_protocol_ZksnarkRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.internal_static_protocol_ZksnarkRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest.class, org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest.Builder.class);
      }

      // Construct using org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (transactionBuilder_ == null) {
          transaction_ = null;
        } else {
          transaction_ = null;
          transactionBuilder_ = null;
        }
        sighash_ = com.google.protobuf.ByteString.EMPTY;

        valueBalance_ = 0L;

        txId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.internal_static_protocol_ZksnarkRequest_descriptor;
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest getDefaultInstanceForType() {
        return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest build() {
        org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest buildPartial() {
        org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest result = new org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest(this);
        if (transactionBuilder_ == null) {
          result.transaction_ = transaction_;
        } else {
          result.transaction_ = transactionBuilder_.build();
        }
        result.sighash_ = sighash_;
        result.valueBalance_ = valueBalance_;
        result.txId_ = txId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest) {
          return mergeFrom((org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest other) {
        if (other == org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest.getDefaultInstance()) return this;
        if (other.hasTransaction()) {
          mergeTransaction(other.getTransaction());
        }
        if (other.getSighash() != com.google.protobuf.ByteString.EMPTY) {
          setSighash(other.getSighash());
        }
        if (other.getValueBalance() != 0L) {
          setValueBalance(other.getValueBalance());
        }
        if (!other.getTxId().isEmpty()) {
          txId_ = other.txId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.tron.sunio.tronsdk.protos.Protocol.Transaction transaction_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.tron.sunio.tronsdk.protos.Protocol.Transaction, org.tron.sunio.tronsdk.protos.Protocol.Transaction.Builder, org.tron.sunio.tronsdk.protos.Protocol.TransactionOrBuilder> transactionBuilder_;
      /**
       * <code>.protocol.Transaction transaction = 1;</code>
       * @return Whether the transaction field is set.
       */
      public boolean hasTransaction() {
        return transactionBuilder_ != null || transaction_ != null;
      }
      /**
       * <code>.protocol.Transaction transaction = 1;</code>
       * @return The transaction.
       */
      public org.tron.sunio.tronsdk.protos.Protocol.Transaction getTransaction() {
        if (transactionBuilder_ == null) {
          return transaction_ == null ? org.tron.sunio.tronsdk.protos.Protocol.Transaction.getDefaultInstance() : transaction_;
        } else {
          return transactionBuilder_.getMessage();
        }
      }
      /**
       * <code>.protocol.Transaction transaction = 1;</code>
       */
      public Builder setTransaction(org.tron.sunio.tronsdk.protos.Protocol.Transaction value) {
        if (transactionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          transaction_ = value;
          onChanged();
        } else {
          transactionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protocol.Transaction transaction = 1;</code>
       */
      public Builder setTransaction(
          org.tron.sunio.tronsdk.protos.Protocol.Transaction.Builder builderForValue) {
        if (transactionBuilder_ == null) {
          transaction_ = builderForValue.build();
          onChanged();
        } else {
          transactionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protocol.Transaction transaction = 1;</code>
       */
      public Builder mergeTransaction(org.tron.sunio.tronsdk.protos.Protocol.Transaction value) {
        if (transactionBuilder_ == null) {
          if (transaction_ != null) {
            transaction_ =
              org.tron.sunio.tronsdk.protos.Protocol.Transaction.newBuilder(transaction_).mergeFrom(value).buildPartial();
          } else {
            transaction_ = value;
          }
          onChanged();
        } else {
          transactionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protocol.Transaction transaction = 1;</code>
       */
      public Builder clearTransaction() {
        if (transactionBuilder_ == null) {
          transaction_ = null;
          onChanged();
        } else {
          transaction_ = null;
          transactionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protocol.Transaction transaction = 1;</code>
       */
      public org.tron.sunio.tronsdk.protos.Protocol.Transaction.Builder getTransactionBuilder() {
        
        onChanged();
        return getTransactionFieldBuilder().getBuilder();
      }
      /**
       * <code>.protocol.Transaction transaction = 1;</code>
       */
      public org.tron.sunio.tronsdk.protos.Protocol.TransactionOrBuilder getTransactionOrBuilder() {
        if (transactionBuilder_ != null) {
          return transactionBuilder_.getMessageOrBuilder();
        } else {
          return transaction_ == null ?
              org.tron.sunio.tronsdk.protos.Protocol.Transaction.getDefaultInstance() : transaction_;
        }
      }
      /**
       * <code>.protocol.Transaction transaction = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.tron.sunio.tronsdk.protos.Protocol.Transaction, org.tron.sunio.tronsdk.protos.Protocol.Transaction.Builder, org.tron.sunio.tronsdk.protos.Protocol.TransactionOrBuilder> 
          getTransactionFieldBuilder() {
        if (transactionBuilder_ == null) {
          transactionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.tron.sunio.tronsdk.protos.Protocol.Transaction, org.tron.sunio.tronsdk.protos.Protocol.Transaction.Builder, org.tron.sunio.tronsdk.protos.Protocol.TransactionOrBuilder>(
                  getTransaction(),
                  getParentForChildren(),
                  isClean());
          transaction_ = null;
        }
        return transactionBuilder_;
      }

      private com.google.protobuf.ByteString sighash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes sighash = 2;</code>
       * @return The sighash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSighash() {
        return sighash_;
      }
      /**
       * <code>bytes sighash = 2;</code>
       * @param value The sighash to set.
       * @return This builder for chaining.
       */
      public Builder setSighash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sighash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes sighash = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSighash() {
        
        sighash_ = getDefaultInstance().getSighash();
        onChanged();
        return this;
      }

      private long valueBalance_ ;
      /**
       * <code>int64 valueBalance = 3;</code>
       * @return The valueBalance.
       */
      @java.lang.Override
      public long getValueBalance() {
        return valueBalance_;
      }
      /**
       * <code>int64 valueBalance = 3;</code>
       * @param value The valueBalance to set.
       * @return This builder for chaining.
       */
      public Builder setValueBalance(long value) {
        
        valueBalance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 valueBalance = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValueBalance() {
        
        valueBalance_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object txId_ = "";
      /**
       * <code>string txId = 4;</code>
       * @return The txId.
       */
      public java.lang.String getTxId() {
        java.lang.Object ref = txId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string txId = 4;</code>
       * @return The bytes for txId.
       */
      public com.google.protobuf.ByteString
          getTxIdBytes() {
        java.lang.Object ref = txId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string txId = 4;</code>
       * @param value The txId to set.
       * @return This builder for chaining.
       */
      public Builder setTxId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string txId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxId() {
        
        txId_ = getDefaultInstance().getTxId();
        onChanged();
        return this;
      }
      /**
       * <code>string txId = 4;</code>
       * @param value The bytes for txId to set.
       * @return This builder for chaining.
       */
      public Builder setTxIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.ZksnarkRequest)
    }

    // @@protoc_insertion_point(class_scope:protocol.ZksnarkRequest)
    private static final org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest();
    }

    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ZksnarkRequest>
        PARSER = new com.google.protobuf.AbstractParser<ZksnarkRequest>() {
      @java.lang.Override
      public ZksnarkRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ZksnarkRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ZksnarkRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ZksnarkRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ZksnarkResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ZksnarkResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.protocol.ZksnarkResponse.Code code = 1;</code>
     * @return The enum numeric value on the wire for code.
     */
    int getCodeValue();
    /**
     * <code>.protocol.ZksnarkResponse.Code code = 1;</code>
     * @return The code.
     */
    org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Code getCode();
  }
  /**
   * Protobuf type {@code protocol.ZksnarkResponse}
   */
  public static final class ZksnarkResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.ZksnarkResponse)
      ZksnarkResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ZksnarkResponse.newBuilder() to construct.
    private ZksnarkResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ZksnarkResponse() {
      code_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ZksnarkResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ZksnarkResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              code_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.internal_static_protocol_ZksnarkResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.internal_static_protocol_ZksnarkResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.class, org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code protocol.ZksnarkResponse.Code}
     */
    public enum Code
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0),
      /**
       * <code>FAILED = 1;</code>
       */
      FAILED(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>FAILED = 1;</code>
       */
      public static final int FAILED_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Code valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Code forNumber(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAILED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Code> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Code>() {
              public Code findValueByNumber(int number) {
                return Code.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Code[] VALUES = values();

      public static Code valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Code(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.ZksnarkResponse.Code)
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>.protocol.ZksnarkResponse.Code code = 1;</code>
     * @return The enum numeric value on the wire for code.
     */
    @java.lang.Override public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.protocol.ZksnarkResponse.Code code = 1;</code>
     * @return The code.
     */
    @java.lang.Override public org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Code getCode() {
      @SuppressWarnings("deprecation")
      org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Code result = org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Code.valueOf(code_);
      return result == null ? org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Code.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Code.SUCCESS.getNumber()) {
        output.writeEnum(1, code_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Code.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse)) {
        return super.equals(obj);
      }
      org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse other = (org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse) obj;

      if (code_ != other.code_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ZksnarkResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ZksnarkResponse)
        org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.internal_static_protocol_ZksnarkResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.internal_static_protocol_ZksnarkResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.class, org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Builder.class);
      }

      // Construct using org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.internal_static_protocol_ZksnarkResponse_descriptor;
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse getDefaultInstanceForType() {
        return org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse build() {
        org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse buildPartial() {
        org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse result = new org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse(this);
        result.code_ = code_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse) {
          return mergeFrom((org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse other) {
        if (other == org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.getDefaultInstance()) return this;
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ = 0;
      /**
       * <code>.protocol.ZksnarkResponse.Code code = 1;</code>
       * @return The enum numeric value on the wire for code.
       */
      @java.lang.Override public int getCodeValue() {
        return code_;
      }
      /**
       * <code>.protocol.ZksnarkResponse.Code code = 1;</code>
       * @param value The enum numeric value on the wire for code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeValue(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.ZksnarkResponse.Code code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Code getCode() {
        @SuppressWarnings("deprecation")
        org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Code result = org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Code.valueOf(code_);
        return result == null ? org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Code.UNRECOGNIZED : result;
      }
      /**
       * <code>.protocol.ZksnarkResponse.Code code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse.Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.ZksnarkResponse.Code code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.ZksnarkResponse)
    }

    // @@protoc_insertion_point(class_scope:protocol.ZksnarkResponse)
    private static final org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse();
    }

    public static org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ZksnarkResponse>
        PARSER = new com.google.protobuf.AbstractParser<ZksnarkResponse>() {
      @java.lang.Override
      public ZksnarkResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ZksnarkResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ZksnarkResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ZksnarkResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tron.sunio.tronsdk.api.ZksnarkGrpcAPI.ZksnarkResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ZksnarkRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ZksnarkRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ZksnarkResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ZksnarkResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021api/zksnark.proto\022\010protocol\032\017core/Tron" +
      ".proto\"q\n\016ZksnarkRequest\022*\n\013transaction\030" +
      "\001 \001(\0132\025.protocol.Transaction\022\017\n\007sighash\030" +
      "\002 \001(\014\022\024\n\014valueBalance\030\003 \001(\003\022\014\n\004txId\030\004 \001(" +
      "\t\"`\n\017ZksnarkResponse\022,\n\004code\030\001 \001(\0162\036.pro" +
      "tocol.ZksnarkResponse.Code\"\037\n\004Code\022\013\n\007SU" +
      "CCESS\020\000\022\n\n\006FAILED\020\0012Y\n\013TronZksnark\022J\n\021Ch" +
      "eckZksnarkProof\022\030.protocol.ZksnarkReques" +
      "t\032\031.protocol.ZksnarkResponse\"\000BV\n\032org.tr" +
      "on.sunio.tronsdk.apiB\016ZksnarkGrpcAPIZ(gi" +
      "thub.com/tronprotocol/grpc-gateway/apib\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tron.sunio.tronsdk.protos.Protocol.getDescriptor(),
        });
    internal_static_protocol_ZksnarkRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_ZksnarkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ZksnarkRequest_descriptor,
        new java.lang.String[] { "Transaction", "Sighash", "ValueBalance", "TxId", });
    internal_static_protocol_ZksnarkResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_ZksnarkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ZksnarkResponse_descriptor,
        new java.lang.String[] { "Code", });
    org.tron.sunio.tronsdk.protos.Protocol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
